apiVersion: v1
name: demo-helm-app
version: 0.1.3
appVersion: "2"
description: Demo Helm App deploy
keywords:
- demo
- helm
- golang
home: https://github.com/grepory/demo-helm-chart
# icon:
sources:
- https://github.com/grepory/demo-helm-chart/charts/demo-helm-app
maintainers:
- name: grepory
  email: greg@notarealemail.com
