apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" . }}-app
  namespace: {{ .Release.Namespace }}
  annotations:
    # When the configuration is changed, this value on the Deployment resource
    # will change, and the deployment will be rolled. See:
    # https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments
    checksum/config: {{ include (print $.Template.BasePath "/config_map.yaml") . | sha256sum }}
  labels:
{{ include "common.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "common.fullname" . }}-app
  template:
    metadata:
      labels:
{{ include "common.template-labels" . | indent 8 }}
        app: {{ include "common.fullname" . }}-app
    spec:
      serviceAccountName: {{ include "common.fullname" . }}-app
      securityContext: {}
      containers:
        - name: app
          securityContext: {}
          image: {{ .Values.demo_helm_app.container_image }}
          command:
            - /app
            - -f /conf/config.yaml
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /message
              port: 80
          readinessProbe:
            httpGet:
              path: /message
              port: 80
          volumeMounts:
            - mountPath: /conf
              name: demo-helm-app-configmap
              readOnly: true
      volumes:
        - name: demo-helm-app-configmap
          configMap:
            name: {{ include "common.fullname" . }}-config
            items:
              - key: config
                path: config.yaml