name: Lint and test charts

on:
  pull_request:
    paths:
      - "charts/**"

jobs:
  lint-test:
    runs-on: ubuntu-latest
    outputs:
      charts: ${{ steps.list-changed.outputs.changed }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
    
      - name: Set up Helm
        uses: azure/setup-helm@v2.1
        with:
          version: v3.10.0
      
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
          check-latest: true
      
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.1
      
      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_STATE
          fi
      
      - name: Run chart-testing (lint)
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        uses: helm/kind-action@v1.4.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        run: ct install

  pr-validated:
    name: pr-validated
    runs-on: ubuntu-latest
    needs:
      - lint-test
    steps:
      - name: validate
        run: echo "PR OK"